BOT_TOKEN = "8199691974:AAFjhrpCCuvgMsK4gFfMUUIRyBQZvqDjYqo"  

LOG_CHAT_ID = "-1002962367553"

OWNER_ID = 7995262033

DB_PATH = "mindscale.db"

MIN_PLAYERS = 5
MAX_PLAYERS = 7
PICK_TIME_SEC = 60
JOIN_TIME_SEC = 150
TARGET_PERCENTAGE = 0.8

LOSER_POINT = -1
ELIMINATION_POINT = -10

RULE_AFTER_1_OUT = True
RULE_AFTER_2_OUT = True
RULE_AFTER_3_OUT = True

# Video placeholders
VIDEO_ROUND_ANNOUNCE = "BAACAgUAAyEFAAS3OY5mAAIH_WjcAQai-HhFDKRdLmAMLxBm27m3AAJVHwAC00rhVpV-sXiybqzWNgQ"
VIDEO_ELIMINATION = "BAACAgUAAyEFAAS3OY5mAAIG_GjcAQWFyh2q8_qgBCE1qFRiIlLxAAJpHgAC00rhVgreiWfsIyY_NgQ"
VIDEO_WINNER = "BAACAgUAAyEFAAS3OY5mAAIG_mjcAQWjT5k0VtEounHroJd-hiHfAAJrHgAC00rhVrBRCwxYF9-UNgQ"

BACKUP_FOLDER = "backups"
Load_id = "CAACAgIAAyEFAAS83kv2AAIDrWj14p4dXB6UngP_jPSOQsYjdGaEAAJdXAEAAWOLRgwCbB8xytx5GTYE"
